storage.bridge_events = storage.bridge_events or {}
local function push(evt)
  table.insert(storage.bridge_events, evt)
  if #storage.bridge_events > 1000 then table.remove(storage.bridge_events, 1) end
end
script.on_event(defines.events.on_research_started, function(e)
  push({type="research_started", name=e.research.name, tick=e.tick})
end)
script.on_event(defines.events.on_research_cancelled, function(e)
  push({type="research_cancelled", name=e.research.name, tick=e.tick})
end)
script.on_event(defines.events.on_player_died, function(e)
  local p=game.get_player(e.player_index)
  local cause=e.cause and e.cause.name or "unknown"
  push({type="player_died", player=p.name, cause=cause, tick=e.tick})
end)
script.on_event(defines.events.on_player_respawned, function(e)
  local p=game.get_player(e.player_index)
  push({type="player_respawned", player=p.name, tick=e.tick})
end)
script.on_event(defines.events.on_player_changed_surface, function(e)
  local p=game.get_player(e.player_index)
  push({type="player_changed_surface", player=p.name, surface=p.surface.name, tick=e.tick})
end)
script.on_event(defines.events.on_player_promoted, function(e)
  local p=game.get_player(e.player_index)
  push({type="player_promoted", player=p.name, tick=e.tick})
end)
script.on_event(defines.events.on_player_demoted, function(e)
  local p=game.get_player(e.player_index)
  push({type="player_demoted", player=p.name, tick=e.tick})
end)
script.on_event(defines.events.on_rocket_launch_ordered, function(e)
  push({type="rocket_launch_ordered", tick=e.tick})
end)
script.on_event(defines.events.on_space_platform_changed_state, function(e)
  local plat=e.platform
  push({type="platform_state_changed", name=plat.name, state=tostring(plat.state), tick=e.tick})
end)
script.on_event(defines.events.on_cargo_pod_finished_ascending, function(e)
  push({type="cargo_ascended", tick=e.tick})
end)
script.on_event(defines.events.on_cargo_pod_finished_descending, function(e)
  push({type="cargo_descended", tick=e.tick})
end)
script.on_event(defines.events.on_entity_died, function(e)
  if e.entity and e.entity.type=="unit-spawner" then
    push({type="spawner_destroyed", name=e.entity.name, tick=e.tick})
  end
end)
script.on_event(defines.events.on_surface_created, function(e)
  local s=game.get_surface(e.surface_index)
  push({type="surface_created", name=s and s.name or "unknown", tick=e.tick})
end)
script.on_event(defines.events.on_chart_tag_added, function(e)
  push({type="tag_added", text=e.tag.text or "", tick=e.tick})
end)
rcon.print("ok")
